### ISSUE TITLE
the chip seq fails to initialize

### ISSUE THREAD

**Issue by amitpande74** [gdevailly/HeatStarSeq_gh#7] opened 2022-02-14 10:49 UTC

**Comment by gdevailly** [comment] 2022-02-15 08:03
Thanks for the feedback. I can confirm https://joshiweb.cbu.uib.no/HeatStarSeq_gh/application/heatchipseq/ is not launching as intended. I will investigate.

**Comment by gdevailly** [comment] 2022-02-15 15:43
The production server is missing an R package. Sorry about that. It should be fixed in about a week.

**Comment by gdevailly** [comment] 2022-02-17 10:49
I believe it is now fixed. The ChIPseq application looks like its working as intended.

**Closed as completed by gdevailly** 2022-02-17 10:49 UTC
